<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SanCaptcha\Module'                           => __DIR__ . '/Module.php',
    'SanCaptcha\Controller\TestcaptchaController' => __DIR__ . '/src/Test/Controller/TestcaptchaController.php',
    'SanCaptcha\Form\TestCaptchaForm'             => __DIR__ . '/src/Test/Form/TestCaptchaForm.php',
);